### ISSUE TITLE
Replace Task with todo and calender components

### ISSUE THREAD

**Issue by miswah** [miswah/personal-dashboard#1]
## Remove Task Component

- [x] Remove Component files
- [x] Remove all the imports from app module
- [x] Remove from sidebar via menu.ts
