### ISSUE TITLE
Implement Todo API's

### ISSUE THREAD

**Issue by miswah** [miswah/personal-dashboard#20]
- [x] Create Todos
- [x] Update
- [x] Tags for todo
- [ ] button to delete all completed todos
- [x] filters by priority
- [x] filter by tags

**Comment by miswah** [comment]
Still need to do R&D on delete all completed todo's
